import Head from 'next/head'
//import Image from "next/image"

import Layout from '../components/Layout'
//import Social from '../components/Social'


export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Hugo Mendoza</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="h-screen">
        <h2 className="">Hola mundo 2</h2>
      </div>
    
    </Layout>
  )
}
