import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/Layout'

export default function Proyectos() {
  return (
    <Layout>
      <Head>
        <title>Hugo Mendoza - Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h2>Blog</h2>
     
    </Layout>
  )
}