import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/Layout'

export default function Proyectos() {
  return (
    <Layout>
      <Head>
        <title>Hugo Mendoza - Proyectos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Proyectos</h2>
     
    </Layout>
  )
}
